// Entrepreneur Assessment Questions for B2B Platform

export interface EntrepreneurQuestion {
  id: number;
  section: string;
  question: string;
  options: {
    text: string;
    color: "yellow" | "red" | "green" | "blue";
  }[];
}

// 25Q Entrepreneur Assessment
export const entrepreneurQuestions25Q: EntrepreneurQuestion[] = [
  // Section A: Vision & Leadership (Q1–Q5)
  { id: 1, section: "Vision & Leadership", question: "When launching a new venture, I usually…", options: [{ text: "Start building right away", color: "yellow" }, { text: "Share the story to inspire others", color: "red" }, { text: "Develop a structured business model", color: "green" }, { text: "Design an innovative solution", color: "blue" }] },
  { id: 2, section: "Vision & Leadership", question: "As a leader, I'm most focused on…", options: [{ text: "Fast execution and results", color: "yellow" }, { text: "Inspiring my team and investors", color: "red" }, { text: "Building scalable systems", color: "green" }, { text: "Creating something disruptive", color: "blue" }] },
  { id: 3, section: "Vision & Leadership", question: "In investor pitches, I emphasize…", options: [{ text: "Traction and execution speed", color: "yellow" }, { text: "Mission and vision", color: "red" }, { text: "Numbers and logical projections", color: "green" }, { text: "Innovation and uniqueness", color: "blue" }] },
  { id: 4, section: "Vision & Leadership", question: "My biggest strength as a founder is…", options: [{ text: "Acting decisively and getting things done", color: "yellow" }, { text: "Rallying people around the mission", color: "red" }, { text: "Structuring and analyzing carefully", color: "green" }, { text: "Innovating beyond the status quo", color: "blue" }] },
  { id: 5, section: "Vision & Leadership", question: "Co-founders usually describe me as…", options: [{ text: "The executor who drives action", color: "yellow" }, { text: "The motivator who brings energy", color: "red" }, { text: "The strategist who organizes", color: "green" }, { text: "The visionary who invents new ideas", color: "blue" }] },

  // Section B: Team-Building & Collaboration (Q6–Q10)
  { id: 6, section: "Team-Building & Collaboration", question: "In team meetings, I tend to…", options: [{ text: "Push toward decisions and action", color: "yellow" }, { text: "Inspire and energize others", color: "red" }, { text: "Clarify details and structure plans", color: "green" }, { text: "Spark creative brainstorming", color: "blue" }] },
  { id: 7, section: "Team-Building & Collaboration", question: "My teammates rely on me for…", options: [{ text: "Speed and determination", color: "yellow" }, { text: "Energy and vision", color: "red" }, { text: "Organization and structure", color: "green" }, { text: "New ideas and creativity", color: "blue" }] },
  { id: 8, section: "Team-Building & Collaboration", question: "My communication style is…", options: [{ text: "Direct and efficient", color: "yellow" }, { text: "Story-driven and inspiring", color: "red" }, { text: "Clear and data-focused", color: "green" }, { text: "Conceptual and visionary", color: "blue" }] },
  { id: 9, section: "Team-Building & Collaboration", question: "I get frustrated when…", options: [{ text: "Things move too slowly", color: "yellow" }, { text: "People lack energy", color: "red" }, { text: "Plans are messy or illogical", color: "green" }, { text: "Innovation is blocked", color: "blue" }] },
  { id: 10, section: "Team-Building & Collaboration", question: "The culture I want to build is…", options: [{ text: "Execution-focused", color: "yellow" }, { text: "Passionate and mission-driven", color: "red" }, { text: "Structured and reliable", color: "green" }, { text: "Innovative and experimental", color: "blue" }] },

  // Section C: Problem-Solving & Decision-Making (Q11–Q15)
  { id: 11, section: "Problem-Solving & Decision-Making", question: "When faced with a big challenge, I…", options: [{ text: "Act quickly to test solutions", color: "yellow" }, { text: "Motivate others to stay positive", color: "red" }, { text: "Break it down logically", color: "green" }, { text: "Reframe the problem creatively", color: "blue" }] },
  { id: 12, section: "Problem-Solving & Decision-Making", question: "I trust my decisions most when…", options: [{ text: "They deliver immediate results", color: "yellow" }, { text: "They inspire people", color: "red" }, { text: "They are backed by data and logic", color: "green" }, { text: "They create new opportunities", color: "blue" }] },
  { id: 13, section: "Problem-Solving & Decision-Making", question: "My strength in problem-solving is…", options: [{ text: "Speed and resilience", color: "yellow" }, { text: "Motivation and persuasion", color: "red" }, { text: "Analysis and structure", color: "green" }, { text: "Creativity and originality", color: "blue" }] },
  { id: 14, section: "Problem-Solving & Decision-Making", question: "In tough debates, I…", options: [{ text: "Push for quick resolution", color: "yellow" }, { text: "Persuade with energy and vision", color: "red" }, { text: "Use facts and reasoning", color: "green" }, { text: "Offer fresh perspectives", color: "blue" }] },
  { id: 15, section: "Problem-Solving & Decision-Making", question: "If my plan fails, I…", options: [{ text: "Try another route immediately", color: "yellow" }, { text: "Keep the team encouraged", color: "red" }, { text: "Reanalyze step by step", color: "green" }, { text: "Pivot to a bold new idea", color: "blue" }] },

  // Section D: Adaptability & Innovation (Q16–Q20)
  { id: 16, section: "Adaptability & Innovation", question: "When the market shifts, I…", options: [{ text: "Adjust quickly and execute fast", color: "yellow" }, { text: "Keep stakeholders inspired", color: "red" }, { text: "Rework the strategy logically", color: "green" }, { text: "Innovate with new offerings", color: "blue" }] },
  { id: 17, section: "Adaptability & Innovation", question: "I learn best when…", options: [{ text: "I can apply it right away", color: "yellow" }, { text: "It connects to mission and people", color: "red" }, { text: "It's explained step by step", color: "green" }, { text: "It's experimental and creative", color: "blue" }] },
  { id: 18, section: "Adaptability & Innovation", question: "I'm most energized when…", options: [{ text: "Things are moving quickly", color: "yellow" }, { text: "People are passionate and motivated", color: "red" }, { text: "Work is structured and clear", color: "green" }, { text: "There's room to innovate", color: "blue" }] },
  { id: 19, section: "Adaptability & Innovation", question: "The ventures I enjoy most are…", options: [{ text: "Fast-paced and growth-driven", color: "yellow" }, { text: "Purposeful and people-focused", color: "red" }, { text: "Structured and scalable", color: "green" }, { text: "Disruptive and innovative", color: "blue" }] },
  { id: 20, section: "Adaptability & Innovation", question: "If my startup hits a roadblock, I…", options: [{ text: "Act fast to try something new", color: "yellow" }, { text: "Motivate others not to give up", color: "red" }, { text: "Re-plan carefully and systematically", color: "green" }, { text: "Pivot creatively into a new direction", color: "blue" }] },

  // Section E: Self-Awareness & Reflection (Q21–Q25)
  { id: 21, section: "Self-Awareness & Reflection", question: "My biggest entrepreneurial strength is…", options: [{ text: "Taking action and execution", color: "yellow" }, { text: "Inspiring others", color: "red" }, { text: "Logical thinking", color: "green" }, { text: "Creative vision", color: "blue" }] },
  { id: 22, section: "Self-Awareness & Reflection", question: "I measure success by…", options: [{ text: "Speed of growth and traction", color: "yellow" }, { text: "The people I've inspired", color: "red" }, { text: "The systems I've built", color: "green" }, { text: "The innovations I've created", color: "blue" }] },
  { id: 23, section: "Self-Awareness & Reflection", question: "I get frustrated when…", options: [{ text: "Action slows down", color: "yellow" }, { text: "People lack passion", color: "red" }, { text: "Work is disorganized", color: "green" }, { text: "Ideas are shut down", color: "blue" }] },
  { id: 24, section: "Self-Awareness & Reflection", question: "My colleagues/investors usually notice that I…", options: [{ text: "Push things forward fast", color: "yellow" }, { text: "Inspire and energize people", color: "red" }, { text: "Present logic and structure clearly", color: "green" }, { text: "Offer bold, creative ideas", color: "blue" }] },
  { id: 25, section: "Self-Awareness & Reflection", question: "Ultimately, I want to be known as…", options: [{ text: "A founder who executes and scales", color: "yellow" }, { text: "A founder who inspires movements", color: "red" }, { text: "A founder who builds systems that last", color: "green" }, { text: "A founder who disrupts with innovation", color: "blue" }] },
];

// 50Q Entrepreneur Assessment
export const entrepreneurQuestions50Q: EntrepreneurQuestion[] = [
  // Section A: Vision & Leadership (Q1–Q10)
  { id: 1, section: "Vision & Leadership", question: "When launching a new venture, my instinct is to…", options: [{ text: "Start building immediately to test the idea", color: "yellow" }, { text: "Share the story and inspire others to join", color: "red" }, { text: "Build a logical business model", color: "green" }, { text: "Design an innovative solution that stands out", color: "blue" }] },
  { id: 2, section: "Vision & Leadership", question: "A successful founder is someone who…", options: [{ text: "Executes fast and adapts quickly", color: "yellow" }, { text: "Inspires others with vision", color: "red" }, { text: "Structures a scalable, sustainable plan", color: "green" }, { text: "Creates something truly original", color: "blue" }] },
  { id: 3, section: "Vision & Leadership", question: "My strength as a leader is…", options: [{ text: "Taking decisive action", color: "yellow" }, { text: "Motivating and inspiring people", color: "red" }, { text: "Thinking critically and logically", color: "green" }, { text: "Bringing fresh, innovative ideas", color: "blue" }] },
  { id: 4, section: "Vision & Leadership", question: "In pitching to investors, I focus on…", options: [{ text: "Showing traction and execution speed", color: "yellow" }, { text: "Telling a powerful story and vision", color: "red" }, { text: "Presenting data and projections logically", color: "green" }, { text: "Highlighting what makes us unique and innovative", color: "blue" }] },
  { id: 5, section: "Vision & Leadership", question: "My co-founders would describe me as…", options: [{ text: "The one who drives things into action", color: "yellow" }, { text: "The one who motivates and rallies the team", color: "red" }, { text: "The one who structures and analyzes decisions", color: "green" }, { text: "The one who pushes creativity and innovation", color: "blue" }] },
  { id: 6, section: "Vision & Leadership", question: "When the team hesitates, I…", options: [{ text: "Push forward with immediate action", color: "yellow" }, { text: "Lift morale with energy and passion", color: "red" }, { text: "Provide logic and structure to clarify", color: "green" }, { text: "Suggest a bold new direction", color: "blue" }] },
  { id: 7, section: "Vision & Leadership", question: "I feel most satisfied when…", options: [{ text: "We execute fast and deliver results", color: "yellow" }, { text: "People are inspired by our mission", color: "red" }, { text: "The business model makes logical sense", color: "green" }, { text: "We create something groundbreaking", color: "blue" }] },
  { id: 8, section: "Vision & Leadership", question: "My natural leadership style is…", options: [{ text: "Direct and action-focused", color: "yellow" }, { text: "Visionary and motivational", color: "red" }, { text: "Strategic and structured", color: "green" }, { text: "Creative and experimental", color: "blue" }] },
  { id: 9, section: "Vision & Leadership", question: "The hardest part of entrepreneurship is…", options: [{ text: "Waiting instead of acting", color: "yellow" }, { text: "Staying motivated without an audience", color: "red" }, { text: "Operating without structure", color: "green" }, { text: "Following rigid systems", color: "blue" }] },
  { id: 10, section: "Vision & Leadership", question: "When scaling, I prioritize…", options: [{ text: "Fast execution and market entry", color: "yellow" }, { text: "Brand, story, and community engagement", color: "red" }, { text: "Efficient processes and systems", color: "green" }, { text: "Product innovation and differentiation", color: "blue" }] },

  // Section B: Team-Building & Collaboration (Q11–Q20)
  { id: 11, section: "Team-Building & Collaboration", question: "In team meetings, I usually…", options: [{ text: "Drive decisions and action items", color: "yellow" }, { text: "Motivate the group with passion", color: "red" }, { text: "Clarify details and logistics", color: "green" }, { text: "Spark creative brainstorming", color: "blue" }] },
  { id: 12, section: "Team-Building & Collaboration", question: "People rely on me to…", options: [{ text: "Get things done fast", color: "yellow" }, { text: "Inspire and energize them", color: "red" }, { text: "Keep systems organized", color: "green" }, { text: "Offer creative breakthroughs", color: "blue" }] },
  { id: 13, section: "Team-Building & Collaboration", question: "My communication style is…", options: [{ text: "Direct and efficient", color: "yellow" }, { text: "Story-driven and inspiring", color: "red" }, { text: "Clear and data-backed", color: "green" }, { text: "Visionary and conceptual", color: "blue" }] },
  { id: 14, section: "Team-Building & Collaboration", question: "When conflict arises, I…", options: [{ text: "Push toward resolution quickly", color: "yellow" }, { text: "Use positivity and persuasion to unite", color: "red" }, { text: "Analyze both sides logically", color: "green" }, { text: "Reframe the problem creatively", color: "blue" }] },
  { id: 15, section: "Team-Building & Collaboration", question: "My ideal co-founder is someone who…", options: [{ text: "Matches my speed and drive", color: "yellow" }, { text: "Believes deeply in the vision", color: "red" }, { text: "Balances me with structure and logic", color: "green" }, { text: "Brings bold, creative thinking", color: "blue" }] },
  { id: 16, section: "Team-Building & Collaboration", question: "I dislike when teammates…", options: [{ text: "Hesitate without acting", color: "yellow" }, { text: "Lack enthusiasm", color: "red" }, { text: "Skip over important details", color: "green" }, { text: "Resist new ideas", color: "blue" }] },
  { id: 17, section: "Team-Building & Collaboration", question: "My strength in teams is…", options: [{ text: "Driving things forward", color: "yellow" }, { text: "Energizing people around a vision", color: "red" }, { text: "Organizing and planning systematically", color: "green" }, { text: "Innovating and ideating constantly", color: "blue" }] },
  { id: 18, section: "Team-Building & Collaboration", question: "In a partnership, I contribute most by…", options: [{ text: "Getting things executed fast", color: "yellow" }, { text: "Motivating and rallying people", color: "red" }, { text: "Building scalable structures", color: "green" }, { text: "Generating unique solutions", color: "blue" }] },
  { id: 19, section: "Team-Building & Collaboration", question: "For me, culture is…", options: [{ text: "A byproduct of execution and results", color: "yellow" }, { text: "The core energy that drives people", color: "red" }, { text: "The systems that make work smooth", color: "green" }, { text: "The creativity that keeps us ahead", color: "blue" }] },
  { id: 20, section: "Team-Building & Collaboration", question: "I prefer teams that…", options: [{ text: "Move quickly and get things done", color: "yellow" }, { text: "Are passionate and connected", color: "red" }, { text: "Are structured and methodical", color: "green" }, { text: "Are innovative and experimental", color: "blue" }] },

  // Section C: Problem-Solving & Decision-Making (Q21–Q30)
  { id: 21, section: "Problem-Solving & Decision-Making", question: "When solving problems, I first…", options: [{ text: "Act quickly to test a solution", color: "yellow" }, { text: "Rally others to stay motivated", color: "red" }, { text: "Break the issue into logical steps", color: "green" }, { text: "Reframe the problem from a new angle", color: "blue" }] },
  { id: 22, section: "Problem-Solving & Decision-Making", question: "My strength in decision-making is…", options: [{ text: "Confidence to act fast", color: "yellow" }, { text: "Persuasion and motivation", color: "red" }, { text: "Data-driven logic", color: "green" }, { text: "Creative reframing", color: "blue" }] },
  { id: 23, section: "Problem-Solving & Decision-Making", question: "I trust my decisions most when…", options: [{ text: "They drive fast results", color: "yellow" }, { text: "They inspire people", color: "red" }, { text: "They are backed by analysis", color: "green" }, { text: "They create new opportunities", color: "blue" }] },
  { id: 24, section: "Problem-Solving & Decision-Making", question: "When mistakes happen, I…", options: [{ text: "Fix them immediately", color: "yellow" }, { text: "Keep morale high", color: "red" }, { text: "Analyze what went wrong", color: "green" }, { text: "Pivot with a new idea", color: "blue" }] },
  { id: 25, section: "Problem-Solving & Decision-Making", question: "In investor meetings, I focus on…", options: [{ text: "Demonstrating traction and speed", color: "yellow" }, { text: "Inspiring with mission and story", color: "red" }, { text: "Presenting structured financials", color: "green" }, { text: "Showcasing unique innovation", color: "blue" }] },
  { id: 26, section: "Problem-Solving & Decision-Making", question: "I prefer instructions that are…", options: [{ text: "Short and actionable", color: "yellow" }, { text: "Motivating and people-centered", color: "red" }, { text: "Detailed and structured", color: "green" }, { text: "Open-ended and flexible", color: "blue" }] },
  { id: 27, section: "Problem-Solving & Decision-Making", question: "I measure startup success by…", options: [{ text: "Speed of execution", color: "yellow" }, { text: "Impact on people and community", color: "red" }, { text: "Scalability and systems", color: "green" }, { text: "Innovation and originality", color: "blue" }] },
  { id: 28, section: "Problem-Solving & Decision-Making", question: "In tough decisions, I…", options: [{ text: "Act quickly and decisively", color: "yellow" }, { text: "Rally people with passion", color: "red" }, { text: "Think through logic and risks", color: "green" }, { text: "Reimagine new approaches", color: "blue" }] },
  { id: 29, section: "Problem-Solving & Decision-Making", question: "If my plan fails, I…", options: [{ text: "Try another route immediately", color: "yellow" }, { text: "Encourage the team to stay hopeful", color: "red" }, { text: "Reassess systematically", color: "green" }, { text: "Pivot to a creative new idea", color: "blue" }] },
  { id: 30, section: "Problem-Solving & Decision-Making", question: "My biggest contribution in problem-solving is…", options: [{ text: "Determination and speed", color: "yellow" }, { text: "Motivation and persuasion", color: "red" }, { text: "Clarity and structure", color: "green" }, { text: "Creativity and innovation", color: "blue" }] },

  // Section D: Adaptability & Innovation (Q31–Q40)
  { id: 31, section: "Adaptability & Innovation", question: "I handle market changes by…", options: [{ text: "Acting fast to adjust strategies", color: "yellow" }, { text: "Keeping investors/team inspired", color: "red" }, { text: "Reworking business models logically", color: "green" }, { text: "Innovating with new products", color: "blue" }] },
  { id: 32, section: "Adaptability & Innovation", question: "I learn best when…", options: [{ text: "I can test it right away", color: "yellow" }, { text: "It connects to people and purpose", color: "red" }, { text: "It's structured step by step", color: "green" }, { text: "It's experimental and open-ended", color: "blue" }] },
  { id: 33, section: "Adaptability & Innovation", question: "My favorite work tasks involve…", options: [{ text: "Executing and achieving goals", color: "yellow" }, { text: "Inspiring others with mission/brand", color: "red" }, { text: "Building systems and models", color: "green" }, { text: "Designing creative solutions", color: "blue" }] },
  { id: 34, section: "Adaptability & Innovation", question: "I stay motivated when…", options: [{ text: "Progress is visible", color: "yellow" }, { text: "The energy is high around me", color: "red" }, { text: "Systems are structured and clear", color: "green" }, { text: "I get to innovate", color: "blue" }] },
  { id: 35, section: "Adaptability & Innovation", question: "My adaptability comes from…", options: [{ text: "Decisive action regardless of change", color: "yellow" }, { text: "Optimism and motivating others", color: "red" }, { text: "Adjusting logically and step by step", color: "green" }, { text: "Rethinking creatively", color: "blue" }] },
  { id: 36, section: "Adaptability & Innovation", question: "When testing new ideas, I…", options: [{ text: "Prototype quickly", color: "yellow" }, { text: "Sell the vision to get buy-in", color: "red" }, { text: "Research and validate carefully", color: "green" }, { text: "Experiment boldly", color: "blue" }] },
  { id: 37, section: "Adaptability & Innovation", question: "I'm most energized by…", options: [{ text: "Momentum and progress", color: "yellow" }, { text: "Passion and community", color: "red" }, { text: "Structure and problem-solving", color: "green" }, { text: "Imagination and design", color: "blue" }] },
  { id: 38, section: "Adaptability & Innovation", question: "If my startup hits a roadblock, I…", options: [{ text: "Act fast to change direction", color: "yellow" }, { text: "Motivate the team to keep pushing", color: "red" }, { text: "Rework the plan carefully", color: "green" }, { text: "Pivot to an innovative new approach", color: "blue" }] },
  { id: 39, section: "Adaptability & Innovation", question: "The ventures I enjoy most are…", options: [{ text: "Fast-paced and growth-driven", color: "yellow" }, { text: "Visionary and people-focused", color: "red" }, { text: "Structured and scalable", color: "green" }, { text: "Innovative and disruptive", color: "blue" }] },
  { id: 40, section: "Adaptability & Innovation", question: "I thrive when I can…", options: [{ text: "Drive execution and growth", color: "yellow" }, { text: "Inspire others with my mission", color: "red" }, { text: "Organize and systematize", color: "green" }, { text: "Create original products/ideas", color: "blue" }] },

  // Section E: Self-Awareness & Reflection (Q41–Q50)
  { id: 41, section: "Self-Awareness & Reflection", question: "My biggest entrepreneurial strength is…", options: [{ text: "Speed of execution", color: "yellow" }, { text: "Inspiring others", color: "red" }, { text: "Strategic structure", color: "green" }, { text: "Innovation", color: "blue" }] },
  { id: 42, section: "Self-Awareness & Reflection", question: "I get frustrated when…", options: [{ text: "Action slows down", color: "yellow" }, { text: "Energy is missing", color: "red" }, { text: "Plans are disorganized", color: "green" }, { text: "Creativity is limited", color: "blue" }] },
  { id: 43, section: "Self-Awareness & Reflection", question: "I measure success by…", options: [{ text: "What I've executed and built", color: "yellow" }, { text: "How many I've inspired", color: "red" }, { text: "What systems I've scaled", color: "green" }, { text: "What I've innovated", color: "blue" }] },
  { id: 44, section: "Self-Awareness & Reflection", question: "My leadership style is…", options: [{ text: "Execution-focused", color: "yellow" }, { text: "Motivational and visionary", color: "red" }, { text: "Logical and structured", color: "green" }, { text: "Creative and experimental", color: "blue" }] },
  { id: 45, section: "Self-Awareness & Reflection", question: "I gain energy from…", options: [{ text: "Achieving milestones fast", color: "yellow" }, { text: "Sharing vision with others", color: "red" }, { text: "Solving complex problems", color: "green" }, { text: "Imagining the future creatively", color: "blue" }] },
  { id: 46, section: "Self-Awareness & Reflection", question: "The hardest thing for me is…", options: [{ text: "Waiting without acting", color: "yellow" }, { text: "Working without inspiration", color: "red" }, { text: "Operating without structure", color: "green" }, { text: "Following rigid systems", color: "blue" }] },
  { id: 47, section: "Self-Awareness & Reflection", question: "My proudest entrepreneurial moments come when…", options: [{ text: "I launch and scale quickly", color: "yellow" }, { text: "I inspire and build communities", color: "red" }, { text: "I create scalable structures", color: "green" }, { text: "I invent something new", color: "blue" }] },
  { id: 48, section: "Self-Awareness & Reflection", question: "Investors usually notice that I…", options: [{ text: "Drive execution aggressively", color: "yellow" }, { text: "Sell the vision passionately", color: "red" }, { text: "Present logical, structured plans", color: "green" }, { text: "Highlight unique innovation", color: "blue" }] },
  { id: 49, section: "Self-Awareness & Reflection", question: "My role in startups is often…", options: [{ text: "The operator", color: "yellow" }, { text: "The storyteller", color: "red" }, { text: "The strategist", color: "green" }, { text: "The innovator", color: "blue" }] },
  { id: 50, section: "Self-Awareness & Reflection", question: "Ultimately, I want to be known as…", options: [{ text: "A founder who executes and wins", color: "yellow" }, { text: "A founder who inspires movements", color: "red" }, { text: "A founder who structures for scale", color: "green" }, { text: "A founder who disrupts with innovation", color: "blue" }] },
];
