type PlatformLogo = {
  src: string;
  alt: string;
  width?: number;
  height?: number;
};

export const HOMEPAGE_PLATFORM_LOGOS: PlatformLogo[] = [
  { src: 'https://merge-api-public.s3.amazonaws.com/media/ADP_Workforce_Now.png', alt: 'ADP Workforce Now logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Altera.png', alt: 'Altera Payroll logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/bamboo_hr_logo.png', alt: 'BambooHR logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Breathe_Logo.png', alt: 'Breathe logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/CharlieHR.png', alt: 'Charlie logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/ChartHop_Horizontal_Logo-RGB.png', alt: 'ChartHop logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/ClayHR.png', alt: 'ClayHR logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Dayforce.png', alt: 'Dayforce logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Deel.png', alt: 'Deel logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Factorial_Logo_43ixzSV.png', alt: 'Factorial logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Freshteam_color.png', alt: 'Freshteam logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Google_Workspace.png', alt: 'Google Workspace logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Gusto_Logo.png', alt: 'Gusto logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/HiBob.png', alt: 'Hibob logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/HR_Cloud_Logo.png', alt: 'HR Cloud logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/HR_Partner_Logo_jQ38Dax.png', alt: 'HR Partner logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Humaans_Logo.png', alt: 'Humaans logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/insperity_color.png', alt: 'Insperity Premier logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/intellihr_clear_background.png', alt: 'IntelliHR logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Jumpcloud.png', alt: 'JumpCloud logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/lucca_image.png', alt: 'Lucca logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Entra_ID-color_EvlrJqh.png', alt: 'Microsoft Entra ID logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Namely_Logo_F1MZFuC.png', alt: 'Namely logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/nmbrs.png', alt: 'Nmbrs logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Officient_color.png', alt: 'Officient logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Okta_color.png', alt: 'Okta logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/OneLogin.png', alt: 'OneLogin logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Paychex_Logo.png', alt: 'Paychex logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/paycor_color.png', alt: 'Paycor logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/payfit_color.png', alt: 'PayFit logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/paylocity.png', alt: 'Paylocity logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/PeopleHR_Access.png', alt: 'PeopleHR logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Personio_NtKZdFF.png', alt: 'Personio logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/proliant_clear.png', alt: 'Proliant logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/rippling_fA793Ul.png', alt: 'Rippling logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Sage_HR_xjq7RKC.png', alt: 'Sage HR logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/sesame1.png', alt: 'Sesame logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Simployer.png', alt: 'Simployer logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Square_Payroll_Logo.png', alt: 'Square Payroll logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/TriNet.png', alt: 'TriNet logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/TriNet_5we3H1H.png', alt: 'TriNet HR Platform logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/UKG_9Wr7tJ0.png', alt: 'UKG Pro logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/UKG_Cw4e1MU.png', alt: 'UKG Pro Workforce Management logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/UKG_eBVH51N.png', alt: 'UKG Ready logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Workday_Logo.png', alt: 'Workday logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/zoho-people.png', alt: 'Zoho People logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Applicant_Stack_Logo.png', alt: 'ApplicantStack logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Ashby_Logo.png', alt: 'Ashby logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Breezy_HR_Logo.png', alt: 'Breezy logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/CATS_Logo.png', alt: 'CATS logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Clockwork.png', alt: 'Clockwork logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Cornerstone_Logo.png', alt: 'Cornerstone TalentLink logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/EngageATS_color.png', alt: 'EngageATS logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Fountain_Logo.png', alt: 'Fountain logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Greenhouse_Logo_oZ1SOIi.png', alt: 'Greenhouse logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Greenhouse_Logo_oZ1SOIi_C7sdH5O.png', alt: 'Greenhouse Job Board API logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Homerun_Logo.png', alt: 'Homerun logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Jazz_HR_Logo.png', alt: 'JazzHR logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Jobsoid.png', alt: 'Jobsoid logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Jobvite_Logo.png', alt: 'Jobvite logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Lano_Logo.png', alt: 'Lano logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Lever_Logo.png', alt: 'Lever logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Taleo_Logo.png', alt: 'Oracle Taleo logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Polymer_Color.png', alt: 'Polymer logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/RecruiterFlow_Logo.png', alt: 'Recruiterflow logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/SuccessFactors_Logo.png', alt: 'SAP SuccessFactors logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/SmartRecruiters_Logo.png', alt: 'SmartRecruiters logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/TalentLyft2x.png', alt: 'TalentLyft logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/TalentReef_color1.png', alt: 'TalentReef logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Teamtailor_Logo.png', alt: 'Teamtailor logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/tellent_recruitee.png', alt: 'Tellent Recruitee logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/UKG_MmgqS87.png', alt: 'UKG Pro Recruiting logo', width: 160, height: 48 },
  { src: 'https://merge-api-public.s3.amazonaws.com/media/Workable_Logo_HWZFYNd.png', alt: 'Workable logo', width: 160, height: 48 },
];
