export type MergeIntegrationCategory = "hris" | "ats";

export interface SupportedMergeIntegration {
  name: string;
  category: MergeIntegrationCategory;
  integration: string;
}

export const MERGE_CLEARBIT_DOMAIN_MAP: Record<string, string> = {
  "ADP Workforce Now": "adp.com",
  "Altera Payroll": "alterapayroll.com",
  "ApplicantStack": "applicantstack.com",
  "Ashby": "ashbyhq.com",
  "BambooHR": "bamboohr.com",
  "Breathe": "breathehr.com",
  "Breezy": "breezy.hr",
  "CATS": "catsone.com",
  "Charlie": "charliehr.com",
  "ChartHop": "charthop.com",
  "ClayHR": "clayhr.com",
  "Clockwork": "clockworkrecruiting.com",
  "Cornerstone TalentLink": "cornerstoneondemand.com",
  "Dayforce": "dayforce.com",
  "Deel": "deel.com",
  "EngageATS": "engageats.com",
  "Factorial": "factorialhr.com",
  "Fountain": "fountain.com",
  "Freshteam": "freshworks.com",
  "Google Workspace": "google.com",
  "Greenhouse": "greenhouse.io",
  "Greenhouse Job Board API": "greenhouse.io",
  "Gusto": "gusto.com",
  "Hibob": "hibob.com",
  "Homerun": "homerun.co",
  "HR Cloud": "hrcloud.com",
  "HR Partner": "hrpartner.io",
  "Humaans": "humaans.io",
  "Insperity Premier": "insperity.com",
  "IntelliHR": "intellihr.com",
  "JazzHR": "jazzhr.com",
  "Jobsoid": "jobsoid.com",
  "Jobvite": "jobvite.com",
  "JumpCloud": "jumpcloud.com",
  "Lano": "lano.io",
  "Lever": "lever.co",
  "Lucca": "lucca.fr",
  "Microsoft Entra ID": "microsoft.com",
  "Namely": "namely.com",
  "Nmbrs": "nmbrs.com",
  "Officient": "officient.io",
  "Okta": "okta.com",
  "OneLogin": "onelogin.com",
  "Oracle Taleo": "oracle.com",
  "Paychex": "paychex.com",
  "Paycor": "paycor.com",
  "PayFit": "payfit.com",
  "Paylocity": "paylocity.com",
  "PeopleHR": "peoplehr.com",
  "Personio": "personio.com",
  "Polymer": "polymer.co",
  "Proliant": "proliant.com",
  "Recruiterflow": "recruiterflow.com",
  "Rippling": "rippling.com",
  "Sage HR": "sage.com",
  "SAP SuccessFactors": "sap.com",
  "Sesame": "sesamehr.com",
  "Simployer": "simployer.com",
  "SmartRecruiters": "smartrecruiters.com",
  "Square Payroll": "squareup.com",
  "TalentLyft": "talentlyft.com",
  "TalentReef": "talentreef.com",
  "Teamtailor": "teamtailor.com",
  "Tellent Recruitee": "recruitee.com",
  "TriNet": "trinet.com",
  "TriNet HR Platform": "trinet.com",
  "UKG Pro": "ukg.com",
  "UKG Pro Recruiting": "ukg.com",
  "UKG Pro Workforce Management": "ukg.com",
  "UKG Ready": "ukg.com",
  "Workable": "workable.com",
  "Workday": "workday.com",
  "Zoho People": "zoho.com",
};

export const MERGE_HRIS_INTEGRATIONS: SupportedMergeIntegration[] = [
  { name: "ADP Workforce Now", category: "hris", integration: "adp-workforce-now" },
  { name: "Altera Payroll", category: "hris", integration: "altera-payroll" },
  { name: "BambooHR", category: "hris", integration: "bamboohr" },
  { name: "Breathe", category: "hris", integration: "breathe" },
  { name: "Charlie", category: "hris", integration: "charlie" },
  { name: "ChartHop", category: "hris", integration: "charthop" },
  { name: "ClayHR", category: "hris", integration: "clayhr" },
  { name: "Dayforce", category: "hris", integration: "dayforce" },
  { name: "Deel", category: "hris", integration: "deel" },
  { name: "Factorial", category: "hris", integration: "factorial" },
  { name: "Freshteam", category: "hris", integration: "freshteam" },
  { name: "Google Workspace", category: "hris", integration: "google-workspace" },
  { name: "Gusto", category: "hris", integration: "gusto" },
  { name: "Hibob", category: "hris", integration: "hibob" },
  { name: "HR Cloud", category: "hris", integration: "hr-cloud" },
  { name: "HR Partner", category: "hris", integration: "hr-partner" },
  { name: "Humaans", category: "hris", integration: "humaans" },
  { name: "Insperity Premier", category: "hris", integration: "insperity-premier" },
  { name: "IntelliHR", category: "hris", integration: "intellihr" },
  { name: "JumpCloud", category: "hris", integration: "jumpcloud" },
  { name: "Lucca", category: "hris", integration: "lucca" },
  { name: "Microsoft Entra ID", category: "hris", integration: "microsoft-entra-id" },
  { name: "Namely", category: "hris", integration: "namely" },
  { name: "Nmbrs", category: "hris", integration: "nmbrs" },
  { name: "Officient", category: "hris", integration: "officient" },
  { name: "Okta", category: "hris", integration: "okta" },
  { name: "OneLogin", category: "hris", integration: "onelogin" },
  { name: "Paychex", category: "hris", integration: "paychex" },
  { name: "Paycor", category: "hris", integration: "paycor" },
  { name: "PayFit", category: "hris", integration: "payfit" },
  { name: "Paylocity", category: "hris", integration: "paylocity" },
  { name: "PeopleHR", category: "hris", integration: "peoplehr" },
  { name: "Personio", category: "hris", integration: "personio" },
  { name: "Proliant", category: "hris", integration: "proliant" },
  { name: "Rippling", category: "hris", integration: "rippling" },
  { name: "Sage HR", category: "hris", integration: "sage-hr" },
  { name: "Sesame", category: "hris", integration: "sesame" },
  { name: "Simployer", category: "hris", integration: "simployer" },
  { name: "Square Payroll", category: "hris", integration: "square-payroll" },
  { name: "TriNet", category: "hris", integration: "trinet" },
  { name: "TriNet HR Platform", category: "hris", integration: "trinet-hr-platform" },
  { name: "UKG Pro", category: "hris", integration: "ukg-pro" },
  { name: "UKG Pro Workforce Management", category: "hris", integration: "ukg-pro-workforce-management" },
  { name: "UKG Ready", category: "hris", integration: "ukg-ready" },
  { name: "Workday", category: "hris", integration: "workday" },
  { name: "Zoho People", category: "hris", integration: "zoho-people" },
];

export const MERGE_ATS_INTEGRATIONS: SupportedMergeIntegration[] = [
  { name: "ApplicantStack", category: "ats", integration: "applicantstack" },
  { name: "Ashby", category: "ats", integration: "ashby" },
  { name: "BambooHR", category: "ats", integration: "bamboohr" },
  { name: "Breezy", category: "ats", integration: "breezy" },
  { name: "CATS", category: "ats", integration: "cats" },
  { name: "ClayHR", category: "ats", integration: "clayhr" },
  { name: "Clockwork", category: "ats", integration: "clockwork" },
  { name: "Cornerstone TalentLink", category: "ats", integration: "cornerstone-talentlink" },
  { name: "EngageATS", category: "ats", integration: "engageats" },
  { name: "Fountain", category: "ats", integration: "fountain" },
  { name: "Freshteam", category: "ats", integration: "freshteam" },
  { name: "Greenhouse", category: "ats", integration: "greenhouse" },
  { name: "Greenhouse Job Board API", category: "ats", integration: "greenhouse-job-board-api" },
  { name: "Homerun", category: "ats", integration: "homerun" },
  { name: "HR Cloud", category: "ats", integration: "hr-cloud" },
  { name: "JazzHR", category: "ats", integration: "jazzhr" },
  { name: "Jobsoid", category: "ats", integration: "jobsoid" },
  { name: "Jobvite", category: "ats", integration: "jobvite" },
  { name: "Lano", category: "ats", integration: "lano" },
  { name: "Lever", category: "ats", integration: "lever" },
  { name: "Oracle Taleo", category: "ats", integration: "oracle-taleo" },
  { name: "Polymer", category: "ats", integration: "polymer" },
  { name: "Recruiterflow", category: "ats", integration: "recruiterflow" },
  { name: "Sage HR", category: "ats", integration: "sage-hr" },
  { name: "SAP SuccessFactors", category: "ats", integration: "sap-successfactors" },
  { name: "SmartRecruiters", category: "ats", integration: "smartrecruiters" },
  { name: "TalentLyft", category: "ats", integration: "talentlyft" },
  { name: "TalentReef", category: "ats", integration: "talentreef" },
  { name: "Teamtailor", category: "ats", integration: "teamtailor" },
  { name: "Tellent Recruitee", category: "ats", integration: "tellent-recruitee" },
  { name: "UKG Pro Recruiting", category: "ats", integration: "ukg-pro-recruiting" },
  { name: "Workable", category: "ats", integration: "workable" },
  { name: "Workday", category: "ats", integration: "workday" },
];

export const SUPPORTED_MERGE_INTEGRATIONS = [...MERGE_HRIS_INTEGRATIONS, ...MERGE_ATS_INTEGRATIONS];
export const TOTAL_SUPPORTED_MERGE_INTEGRATIONS = SUPPORTED_MERGE_INTEGRATIONS.length;

export const getClearbitLogoUrl = (platformName: string) => {
  const domain = MERGE_CLEARBIT_DOMAIN_MAP[platformName];
  return domain ? `https://logo.clearbit.com/${domain}` : null;
};
