// Professional Assessment Questions for B2B Platform

export interface ProfessionalQuestion {
  id: number;
  section: string;
  question: string;
  options: {
    text: string;
    color: "yellow" | "red" | "green" | "blue";
  }[];
}

// 25Q Professional Assessment
export const professionalQuestions25Q: ProfessionalQuestion[] = [
  // Section A: Leadership & Initiative (Q1–Q5)
  { id: 1, section: "Leadership & Initiative", question: "When starting a new project, I usually…", options: [{ text: "Take immediate action and assign tasks", color: "yellow" }, { text: "Share the bigger vision and energize the team", color: "red" }, { text: "Build a structured plan step by step", color: "green" }, { text: "Brainstorm new and creative approaches", color: "blue" }] },
  { id: 2, section: "Leadership & Initiative", question: "The best leaders…", options: [{ text: "Drive execution and results", color: "yellow" }, { text: "Inspire with passion and communication", color: "red" }, { text: "Provide logic and clarity", color: "green" }, { text: "Innovate and reimagine possibilities", color: "blue" }] },
  { id: 3, section: "Leadership & Initiative", question: "When deadlines approach, I…", options: [{ text: "Push the team into focused action", color: "yellow" }, { text: "Rally people with encouragement and energy", color: "red" }, { text: "Reorganize priorities logically", color: "green" }, { text: "Find creative shortcuts to achieve goals", color: "blue" }] },
  { id: 4, section: "Leadership & Initiative", question: "My colleagues usually describe me as…", options: [{ text: "The one who makes things happen", color: "yellow" }, { text: "The one who motivates and uplifts", color: "red" }, { text: "The one who keeps things organized", color: "green" }, { text: "The one who brings innovative ideas", color: "blue" }] },
  { id: 5, section: "Leadership & Initiative", question: "I feel most accomplished when…", options: [{ text: "Results are achieved quickly", color: "yellow" }, { text: "People are inspired by my work", color: "red" }, { text: "Systems are clear and efficient", color: "green" }, { text: "Something new and original is created", color: "blue" }] },
  
  // Section B: Collaboration & Communication (Q6–Q10)
  { id: 6, section: "Collaboration & Communication", question: "In team discussions, I tend to…", options: [{ text: "Push toward decisions and action", color: "yellow" }, { text: "Motivate and energize others", color: "red" }, { text: "Clarify details and structure", color: "green" }, { text: "Ask bold, creative \"what if\" questions", color: "blue" }] },
  { id: 7, section: "Collaboration & Communication", question: "My teammates rely on me for…", options: [{ text: "Speed and reliability", color: "yellow" }, { text: "Energy and encouragement", color: "red" }, { text: "Organization and logic", color: "green" }, { text: "Creative problem-solving", color: "blue" }] },
  { id: 8, section: "Collaboration & Communication", question: "My communication style is…", options: [{ text: "Direct and action-oriented", color: "yellow" }, { text: "Enthusiastic and persuasive", color: "red" }, { text: "Clear and precise", color: "green" }, { text: "Conceptual and visionary", color: "blue" }] },
  { id: 9, section: "Collaboration & Communication", question: "I get frustrated when…", options: [{ text: "Projects stall without action", color: "yellow" }, { text: "People lack passion or motivation", color: "red" }, { text: "Details are overlooked", color: "green" }, { text: "Innovation is resisted", color: "blue" }] },
  { id: 10, section: "Collaboration & Communication", question: "My role in teams is usually…", options: [{ text: "The driver who executes", color: "yellow" }, { text: "The motivator who inspires", color: "red" }, { text: "The organizer who structures", color: "green" }, { text: "The innovator who creates", color: "blue" }] },
  
  // Section C: Problem-Solving & Decision-Making (Q11–Q15)
  { id: 11, section: "Problem-Solving & Decision-Making", question: "When solving problems, my first step is to…", options: [{ text: "Act quickly and test a solution", color: "yellow" }, { text: "Motivate others to stay positive", color: "red" }, { text: "Break it down into logical steps", color: "green" }, { text: "Reframe the issue creatively", color: "blue" }] },
  { id: 12, section: "Problem-Solving & Decision-Making", question: "I trust decisions when…", options: [{ text: "They produce fast results", color: "yellow" }, { text: "They inspire and energize others", color: "red" }, { text: "They are backed by logic and data", color: "green" }, { text: "They open new opportunities", color: "blue" }] },
  { id: 13, section: "Problem-Solving & Decision-Making", question: "My problem-solving strength is…", options: [{ text: "Speed and determination", color: "yellow" }, { text: "Motivation and optimism", color: "red" }, { text: "Structure and clarity", color: "green" }, { text: "Creativity and originality", color: "blue" }] },
  { id: 14, section: "Problem-Solving & Decision-Making", question: "In debates, I…", options: [{ text: "Push for a resolution quickly", color: "yellow" }, { text: "Persuade with passion and stories", color: "red" }, { text: "Use facts and logic", color: "green" }, { text: "Share new perspectives and ideas", color: "blue" }] },
  { id: 15, section: "Problem-Solving & Decision-Making", question: "If my plan fails, I…", options: [{ text: "Try another approach immediately", color: "yellow" }, { text: "Encourage others not to give up", color: "red" }, { text: "Reanalyze carefully step by step", color: "green" }, { text: "Redesign it with creativity", color: "blue" }] },
  
  // Section D: Adaptability & Innovation (Q16–Q20)
  { id: 16, section: "Adaptability & Innovation", question: "When unexpected changes happen, I…", options: [{ text: "Adjust quickly and keep moving", color: "yellow" }, { text: "Stay positive and encourage others", color: "red" }, { text: "Re-plan logically", color: "green" }, { text: "Pivot to a creative alternative", color: "blue" }] },
  { id: 17, section: "Adaptability & Innovation", question: "I learn best when…", options: [{ text: "I can apply it immediately", color: "yellow" }, { text: "It connects to purpose and people", color: "red" }, { text: "It's explained step by step", color: "green" }, { text: "It allows me to experiment", color: "blue" }] },
  { id: 18, section: "Adaptability & Innovation", question: "I'm most energized when…", options: [{ text: "Projects are moving fast", color: "yellow" }, { text: "People are motivated and connected", color: "red" }, { text: "Work is organized and structured", color: "green" }, { text: "There's space to innovate", color: "blue" }] },
  { id: 19, section: "Adaptability & Innovation", question: "The workplace projects I enjoy most are…", options: [{ text: "Goal-driven and fast-paced", color: "yellow" }, { text: "Energizing and people-centered", color: "red" }, { text: "Structured and methodical", color: "green" }, { text: "Open-ended and innovative", color: "blue" }] },
  { id: 20, section: "Adaptability & Innovation", question: "If plans are interrupted, I…", options: [{ text: "Act quickly with a backup", color: "yellow" }, { text: "Keep others motivated", color: "red" }, { text: "Re-plan step by step", color: "green" }, { text: "Pivot to a fresh idea", color: "blue" }] },
  
  // Section E: Self-Awareness & Reflection (Q21–Q25)
  { id: 21, section: "Self-Awareness & Reflection", question: "My biggest professional strength is…", options: [{ text: "Getting things done", color: "yellow" }, { text: "Inspiring others", color: "red" }, { text: "Thinking logically", color: "green" }, { text: "Creating new ideas", color: "blue" }] },
  { id: 22, section: "Self-Awareness & Reflection", question: "I measure success by…", options: [{ text: "The results achieved", color: "yellow" }, { text: "The people inspired", color: "red" }, { text: "The systems improved", color: "green" }, { text: "The innovations created", color: "blue" }] },
  { id: 23, section: "Self-Awareness & Reflection", question: "I get frustrated when…", options: [{ text: "Action is delayed", color: "yellow" }, { text: "Passion is missing", color: "red" }, { text: "Plans lack structure", color: "green" }, { text: "Creativity is blocked", color: "blue" }] },
  { id: 24, section: "Self-Awareness & Reflection", question: "My colleagues usually notice that I…", options: [{ text: "Drive things into action", color: "yellow" }, { text: "Motivate with enthusiasm", color: "red" }, { text: "Keep things organized", color: "green" }, { text: "Offer creative ideas", color: "blue" }] },
  { id: 25, section: "Self-Awareness & Reflection", question: "Ultimately, I want to be known as…", options: [{ text: "A doer who delivers results", color: "yellow" }, { text: "A motivator who inspires others", color: "red" }, { text: "A thinker who brings order", color: "green" }, { text: "A creator who innovates", color: "blue" }] },
];

// 50Q Professional Assessment
export const professionalQuestions50Q: ProfessionalQuestion[] = [
  // Section A: Leadership & Initiative (Q1–Q10)
  { id: 1, section: "Leadership & Initiative", question: "When starting a new project, I usually…", options: [{ text: "Break tasks into actions and move forward immediately", color: "yellow" }, { text: "Share the vision and inspire the team", color: "red" }, { text: "Build a step-by-step structure", color: "green" }, { text: "Brainstorm innovative approaches before starting", color: "blue" }] },
  { id: 2, section: "Leadership & Initiative", question: "The best leaders…", options: [{ text: "Drive results through action", color: "yellow" }, { text: "Inspire with passion and communication", color: "red" }, { text: "Create clarity through logic and organization", color: "green" }, { text: "Push innovation and reimagine possibilities", color: "blue" }] },
  { id: 3, section: "Leadership & Initiative", question: "When a deadline is approaching, I…", options: [{ text: "Push to get things done quickly", color: "yellow" }, { text: "Rally the team with energy and motivation", color: "red" }, { text: "Re-prioritize tasks logically", color: "green" }, { text: "Find creative ways to meet the goal", color: "blue" }] },
  { id: 4, section: "Leadership & Initiative", question: "I feel most accomplished when…", options: [{ text: "A project is executed successfully", color: "yellow" }, { text: "People are inspired by my work", color: "red" }, { text: "Processes are optimized and efficient", color: "green" }, { text: "We create something new and original", color: "blue" }] },
  { id: 5, section: "Leadership & Initiative", question: "My colleagues usually describe me as…", options: [{ text: "The one who makes things happen", color: "yellow" }, { text: "The one who lifts morale and inspires", color: "red" }, { text: "The one who keeps things organized", color: "green" }, { text: "The one who brings creative ideas", color: "blue" }] },
  { id: 6, section: "Leadership & Initiative", question: "In leadership, I value most…", options: [{ text: "Efficiency and action", color: "yellow" }, { text: "Energy and vision", color: "red" }, { text: "Structure and clarity", color: "green" }, { text: "Innovation and experimentation", color: "blue" }] },
  { id: 7, section: "Leadership & Initiative", question: "When others are uncertain, I…", options: [{ text: "Decide quickly and act", color: "yellow" }, { text: "Encourage them with positivity", color: "red" }, { text: "Provide data and logic", color: "green" }, { text: "Suggest new ways forward", color: "blue" }] },
  { id: 8, section: "Leadership & Initiative", question: "My natural instinct is to…", options: [{ text: "Act first and adjust later", color: "yellow" }, { text: "Inspire with stories and energy", color: "red" }, { text: "Analyze carefully before moving ahead", color: "green" }, { text: "Explore new, unconventional ideas", color: "blue" }] },
  { id: 9, section: "Leadership & Initiative", question: "Success in leadership means…", options: [{ text: "Achieving results consistently", color: "yellow" }, { text: "Motivating people to reach their best", color: "red" }, { text: "Building reliable systems", color: "green" }, { text: "Creating a culture of innovation", color: "blue" }] },
  { id: 10, section: "Leadership & Initiative", question: "When a project begins, I focus on…", options: [{ text: "Defining immediate next steps", color: "yellow" }, { text: "Sharing the vision and purpose", color: "red" }, { text: "Establishing structure and timelines", color: "green" }, { text: "Designing creative strategies to differentiate", color: "blue" }] },
  
  // Section B: Collaboration & Communication (Q11–Q20)
  { id: 11, section: "Collaboration & Communication", question: "In team discussions, I…", options: [{ text: "Push for decisions and action", color: "yellow" }, { text: "Motivate others with energy", color: "red" }, { text: "Clarify details and organize thoughts", color: "green" }, { text: "Ask innovative, \"what if\" questions", color: "blue" }] },
  { id: 12, section: "Collaboration & Communication", question: "My teammates rely on me to…", options: [{ text: "Get things done under pressure", color: "yellow" }, { text: "Inspire and energize the group", color: "red" }, { text: "Keep the project on track and structured", color: "green" }, { text: "Spot creative opportunities", color: "blue" }] },
  { id: 13, section: "Collaboration & Communication", question: "My communication style is…", options: [{ text: "Direct and action-oriented", color: "yellow" }, { text: "Enthusiastic and persuasive", color: "red" }, { text: "Precise and logical", color: "green" }, { text: "Conceptual and forward-looking", color: "blue" }] },
  { id: 14, section: "Collaboration & Communication", question: "If conflict arises, I…", options: [{ text: "Push toward a fast resolution", color: "yellow" }, { text: "Use positivity to bring people together", color: "red" }, { text: "Analyze both perspectives logically", color: "green" }, { text: "Reframe with a creative solution", color: "blue" }] },
  { id: 15, section: "Collaboration & Communication", question: "I contribute best when…", options: [{ text: "Driving projects into action", color: "yellow" }, { text: "Inspiring people toward goals", color: "red" }, { text: "Creating order and clarity", color: "green" }, { text: "Bringing fresh, creative ideas", color: "blue" }] },
  { id: 16, section: "Collaboration & Communication", question: "My colleagues count on me for…", options: [{ text: "Speed and reliability", color: "yellow" }, { text: "Enthusiasm and morale-boosting", color: "red" }, { text: "Accuracy and structure", color: "green" }, { text: "Vision and creative problem-solving", color: "blue" }] },
  { id: 17, section: "Collaboration & Communication", question: "I dislike when team members…", options: [{ text: "Waste time without acting", color: "yellow" }, { text: "Lack energy or motivation", color: "red" }, { text: "Ignore important details", color: "green" }, { text: "Resist new ideas", color: "blue" }] },
  { id: 18, section: "Collaboration & Communication", question: "In presentations, I prefer to…", options: [{ text: "Share results and progress", color: "yellow" }, { text: "Inspire the audience with passion", color: "red" }, { text: "Explain the logic and data clearly", color: "green" }, { text: "Highlight innovative, creative elements", color: "blue" }] },
  { id: 19, section: "Collaboration & Communication", question: "I usually motivate colleagues by…", options: [{ text: "Showing momentum and results", color: "yellow" }, { text: "Sharing an inspiring vision", color: "red" }, { text: "Explaining clear steps", color: "green" }, { text: "Suggesting bold new directions", color: "blue" }] },
  { id: 20, section: "Collaboration & Communication", question: "My team role is often…", options: [{ text: "The driver", color: "yellow" }, { text: "The motivator", color: "red" }, { text: "The organizer", color: "green" }, { text: "The innovator", color: "blue" }] },
  
  // Section C: Problem-Solving & Decision-Making (Q21–Q30)
  { id: 21, section: "Problem-Solving & Decision-Making", question: "When solving problems, I first…", options: [{ text: "Jump into action to test solutions", color: "yellow" }, { text: "Motivate others to stay positive", color: "red" }, { text: "Break the issue into logical steps", color: "green" }, { text: "Explore alternative, creative options", color: "blue" }] },
  { id: 22, section: "Problem-Solving & Decision-Making", question: "My strength in decision-making is…", options: [{ text: "Acting quickly with confidence", color: "yellow" }, { text: "Persuading with energy and vision", color: "red" }, { text: "Using facts and analysis", color: "green" }, { text: "Reframing challenges innovatively", color: "blue" }] },
  { id: 23, section: "Problem-Solving & Decision-Making", question: "I trust decisions when…", options: [{ text: "They create fast results", color: "yellow" }, { text: "They inspire others", color: "red" }, { text: "They are supported by data", color: "green" }, { text: "They open new opportunities", color: "blue" }] },
  { id: 24, section: "Problem-Solving & Decision-Making", question: "When a mistake happens, I…", options: [{ text: "Fix it immediately and move on", color: "yellow" }, { text: "Keep morale high and encourage the team", color: "red" }, { text: "Analyze carefully what went wrong", color: "green" }, { text: "Pivot into a new solution creatively", color: "blue" }] },
  { id: 25, section: "Problem-Solving & Decision-Making", question: "In high-pressure situations, I…", options: [{ text: "Take control and push forward", color: "yellow" }, { text: "Motivate others to stay calm and positive", color: "red" }, { text: "Focus on logic and steps", color: "green" }, { text: "Look for unconventional alternatives", color: "blue" }] },
  { id: 26, section: "Problem-Solving & Decision-Making", question: "I prefer instructions that are…", options: [{ text: "Clear and actionable", color: "yellow" }, { text: "Inspirational and people-centered", color: "red" }, { text: "Detailed and systematic", color: "green" }, { text: "Flexible and open-ended", color: "blue" }] },
  { id: 27, section: "Problem-Solving & Decision-Making", question: "I measure success by…", options: [{ text: "Achieving tangible results", color: "yellow" }, { text: "Inspiring and influencing people", color: "red" }, { text: "Accuracy and effectiveness", color: "green" }, { text: "Originality and innovation", color: "blue" }] },
  { id: 28, section: "Problem-Solving & Decision-Making", question: "In decision-making groups, I…", options: [{ text: "Push for fast decisions", color: "yellow" }, { text: "Advocate passionately for ideas", color: "red" }, { text: "Provide logic and structure", color: "green" }, { text: "Introduce new perspectives", color: "blue" }] },
  { id: 29, section: "Problem-Solving & Decision-Making", question: "If my idea fails, I…", options: [{ text: "Try something else quickly", color: "yellow" }, { text: "Keep others motivated to try again", color: "red" }, { text: "Reanalyze carefully", color: "green" }, { text: "Redesign the idea innovatively", color: "blue" }] },
  { id: 30, section: "Problem-Solving & Decision-Making", question: "My biggest contribution in problem-solving is…", options: [{ text: "Speed and determination", color: "yellow" }, { text: "Inspiration and communication", color: "red" }, { text: "Structure and clarity", color: "green" }, { text: "Creativity and originality", color: "blue" }] },
  
  // Section D: Adaptability & Innovation (Q31–Q40)
  { id: 31, section: "Adaptability & Innovation", question: "I handle unexpected changes by…", options: [{ text: "Acting quickly to adjust", color: "yellow" }, { text: "Keeping the team positive", color: "red" }, { text: "Reworking plans step by step", color: "green" }, { text: "Pivoting to a new creative solution", color: "blue" }] },
  { id: 32, section: "Adaptability & Innovation", question: "I learn best when…", options: [{ text: "I can apply it right away", color: "yellow" }, { text: "It connects to people and purpose", color: "red" }, { text: "It's structured and systematic", color: "green" }, { text: "It's open to creative exploration", color: "blue" }] },
  { id: 33, section: "Adaptability & Innovation", question: "I enjoy projects that are…", options: [{ text: "Fast-paced and goal-driven", color: "yellow" }, { text: "Inspiring and people-focused", color: "red" }, { text: "Structured and methodical", color: "green" }, { text: "Open-ended and innovative", color: "blue" }] },
  { id: 34, section: "Adaptability & Innovation", question: "I stay motivated when…", options: [{ text: "Progress is visible", color: "yellow" }, { text: "The energy around me is high", color: "red" }, { text: "The work is organized logically", color: "green" }, { text: "I get to innovate and create", color: "blue" }] },
  { id: 35, section: "Adaptability & Innovation", question: "My adaptability comes from…", options: [{ text: "Taking decisive action", color: "yellow" }, { text: "Staying optimistic and encouraging others", color: "red" }, { text: "Adjusting logically step by step", color: "green" }, { text: "Rethinking situations creatively", color: "blue" }] },
  { id: 36, section: "Adaptability & Innovation", question: "When trying new methods, I…", options: [{ text: "Test them quickly in practice", color: "yellow" }, { text: "Share enthusiasm to get buy-in", color: "red" }, { text: "Research carefully before implementing", color: "green" }, { text: "Experiment and see what happens", color: "blue" }] },
  { id: 37, section: "Adaptability & Innovation", question: "I'm most energized by…", options: [{ text: "Momentum and results", color: "yellow" }, { text: "Passion and connection", color: "red" }, { text: "Order and structure", color: "green" }, { text: "Creativity and vision", color: "blue" }] },
  { id: 38, section: "Adaptability & Innovation", question: "If a plan fails, I…", options: [{ text: "Act fast to try a new one", color: "yellow" }, { text: "Motivate others not to give up", color: "red" }, { text: "Re-plan carefully", color: "green" }, { text: "Invent an alternative", color: "blue" }] },
  { id: 39, section: "Adaptability & Innovation", question: "The workplace projects I enjoy most are…", options: [{ text: "Execution-focused", color: "yellow" }, { text: "People-centered and energizing", color: "red" }, { text: "Structured and organized", color: "green" }, { text: "Innovative and exploratory", color: "blue" }] },
  { id: 40, section: "Adaptability & Innovation", question: "I thrive when I can…", options: [{ text: "Take decisive action", color: "yellow" }, { text: "Inspire and influence others", color: "red" }, { text: "Organize systems and processes", color: "green" }, { text: "Create and innovate freely", color: "blue" }] },
  
  // Section E: Self-Awareness & Reflection (Q41–Q50)
  { id: 41, section: "Self-Awareness & Reflection", question: "My biggest strength is…", options: [{ text: "Taking action and execution", color: "yellow" }, { text: "Inspiring others", color: "red" }, { text: "Logical problem-solving", color: "green" }, { text: "Creative thinking", color: "blue" }] },
  { id: 42, section: "Self-Awareness & Reflection", question: "I get frustrated when…", options: [{ text: "Work stalls without action", color: "yellow" }, { text: "Energy and passion are missing", color: "red" }, { text: "Systems are unclear", color: "green" }, { text: "Innovation is shut down", color: "blue" }] },
  { id: 43, section: "Self-Awareness & Reflection", question: "I measure my growth by…", options: [{ text: "The results I've achieved", color: "yellow" }, { text: "The people I've inspired", color: "red" }, { text: "The knowledge and skills I've built", color: "green" }, { text: "The innovations I've created", color: "blue" }] },
  { id: 44, section: "Self-Awareness & Reflection", question: "My leadership style is…", options: [{ text: "Action-driven", color: "yellow" }, { text: "Visionary and motivational", color: "red" }, { text: "Structured and logical", color: "green" }, { text: "Creative and future-focused", color: "blue" }] },
  { id: 45, section: "Self-Awareness & Reflection", question: "I gain energy from…", options: [{ text: "Achieving milestones", color: "yellow" }, { text: "Connecting with and inspiring others", color: "red" }, { text: "Solving complex problems", color: "green" }, { text: "Imagining new possibilities", color: "blue" }] },
  { id: 46, section: "Self-Awareness & Reflection", question: "The hardest thing for me is…", options: [{ text: "Waiting without acting", color: "yellow" }, { text: "Working without inspiration", color: "red" }, { text: "Functioning without structure", color: "green" }, { text: "Following rigid rules", color: "blue" }] },
  { id: 47, section: "Self-Awareness & Reflection", question: "My proudest professional moments come when…", options: [{ text: "I execute big wins", color: "yellow" }, { text: "I inspire and uplift others", color: "red" }, { text: "I solve complex challenges", color: "green" }, { text: "I innovate something new", color: "blue" }] },
  { id: 48, section: "Self-Awareness & Reflection", question: "Colleagues usually notice that I…", options: [{ text: "Get things moving quickly", color: "yellow" }, { text: "Bring energy and inspiration", color: "red" }, { text: "Keep things organized", color: "green" }, { text: "Suggest creative ideas", color: "blue" }] },
  { id: 49, section: "Self-Awareness & Reflection", question: "My preferred role in a team is…", options: [{ text: "Driver", color: "yellow" }, { text: "Motivator", color: "red" }, { text: "Organizer", color: "green" }, { text: "Innovator", color: "blue" }] },
  { id: 50, section: "Self-Awareness & Reflection", question: "Ultimately, I want to be known as…", options: [{ text: "A doer who gets results", color: "yellow" }, { text: "A motivator who inspires people", color: "red" }, { text: "A thinker who builds order", color: "green" }, { text: "A creator who innovates the future", color: "blue" }] },
];
