export interface StudentQuestion {
  id: number;
  section: string;
  question: string;
  options: {
    A: string;
    B: string;
    C: string;
    D: string;
  };
}

export const studentAssessmentQuestions: StudentQuestion[] = [
  // SECTION 1 — School Values & Student Philosophy
  { id: 1, section: "School Values & Student Philosophy", question: "Which quality do you most want students to develop?", options: { A: "Creativity", B: "Motivation", C: "Organization", D: "Productivity" } },
  { id: 2, section: "School Values & Student Philosophy", question: "What defines a \"successful student\" at your school?", options: { A: "Thinks innovatively", B: "Builds relationships", C: "Stays structured", D: "Gets things done" } },
  { id: 3, section: "School Values & Student Philosophy", question: "Which student strength should the assessment measure most?", options: { A: "Creative thinking", B: "Social-emotional competence", C: "Planning and study skills", D: "Work ethic" } },
  { id: 4, section: "School Values & Student Philosophy", question: "What student behavior most aligns with your school's mission?", options: { A: "Original ideas", B: "Positive interactions", C: "Preparedness", D: "Strong follow-through" } },
  { id: 5, section: "School Values & Student Philosophy", question: "Where do you want students to grow most?", options: { A: "Creative confidence", B: "Emotional intelligence", C: "Organizational habits", D: "Academic drive" } },
  { id: 6, section: "School Values & Student Philosophy", question: "Which tendency do you want students to understand better?", options: { A: "How they generate ideas", B: "How they connect with others", C: "How they organize tasks", D: "How they take action" } },
  { id: 7, section: "School Values & Student Philosophy", question: "The school's culture is strongest when students:", options: { A: "Think outside the box", B: "Support each other", C: "Follow routines", D: "Stay on-task" } },
  { id: 8, section: "School Values & Student Philosophy", question: "The student report should highlight strengths in:", options: { A: "Innovation", B: "Collaboration", C: "Executive functioning", D: "Persistence" } },
  { id: 9, section: "School Values & Student Philosophy", question: "Where do you see the most student struggles?", options: { A: "Creativity blocks", B: "Peer relationships", C: "Organization", D: "Motivation" } },
  { id: 10, section: "School Values & Student Philosophy", question: "What do students need more support understanding?", options: { A: "Creative identity", B: "Social identity", C: "Work habits", D: "Academic performance" } },
  { id: 11, section: "School Values & Student Philosophy", question: "Which challenge most affects student success?", options: { A: "Lack of ideas", B: "Social stress", C: "Disorganization", D: "Procrastination" } },
  { id: 12, section: "School Values & Student Philosophy", question: "The student assessment should encourage students to:", options: { A: "Try new approaches", B: "Build healthy relationships", C: "Plan their work", D: "Take action" } },
  { id: 13, section: "School Values & Student Philosophy", question: "Your school values students who:", options: { A: "Are imaginative", B: "Are kind", C: "Are prepared", D: "Are efficient" } },
  { id: 14, section: "School Values & Student Philosophy", question: "You want a student report that feels:", options: { A: "Creative", B: "Encouraging", C: "Structured", D: "Practical" } },
  { id: 15, section: "School Values & Student Philosophy", question: "Student growth conversations should frame strengths as:", options: { A: "Creative gifts", B: "Social skills", C: "Organizational habits", D: "Work ethic" } },

  // SECTION 2 — Academic Skill Priorities
  { id: 16, section: "Academic Skill Priorities", question: "Which academic skill should the assessment emphasize?", options: { A: "Creative problem-solving", B: "Engagement & participation", C: "Planning & study skills", D: "Task execution" } },
  { id: 17, section: "Academic Skill Priorities", question: "Student academic struggles often come from:", options: { A: "Being unsure how to start creatively", B: "Low motivation", C: "Weak organization", D: "Inconsistent effort" } },
  { id: 18, section: "Academic Skill Priorities", question: "What is the most common academic weakness?", options: { A: "Idea development", B: "Attention & engagement", C: "Planning", D: "Completion" } },
  { id: 19, section: "Academic Skill Priorities", question: "What should the student report clearly define?", options: { A: "Creative strengths", B: "Motivational patterns", C: "Organization style", D: "Productivity habits" } },
  { id: 20, section: "Academic Skill Priorities", question: "Your students need the MOST support with:", options: { A: "Generating ideas", B: "Sustaining motivation", C: "Planning assignments", D: "Completing assignments" } },
  { id: 21, section: "Academic Skill Priorities", question: "Student achievement improves most when they:", options: { A: "Think creatively", B: "Stay motivated", C: "Stay organized", D: "Work consistently" } },
  { id: 22, section: "Academic Skill Priorities", question: "You want the assessment to measure how students:", options: { A: "Approach creative tasks", B: "Approach social dynamics", C: "Approach planning", D: "Approach academic tasks" } },
  { id: 23, section: "Academic Skill Priorities", question: "Which habit do you want highlighted?", options: { A: "Curiosity", B: "Engagement", C: "Preparedness", D: "Productivity" } },
  { id: 24, section: "Academic Skill Priorities", question: "Academic failure most often stems from:", options: { A: "Idea overwhelm", B: "Emotional challenges", C: "Lack of planning", D: "Lack of action" } },
  { id: 25, section: "Academic Skill Priorities", question: "Students would grow academically if they improved:", options: { A: "Innovation", B: "Motivation", C: "Organization", D: "Execution" } },
  { id: 26, section: "Academic Skill Priorities", question: "Teachers want more insight into student:", options: { A: "Creativity", B: "Participation", C: "Organization", D: "Work completion" } },
  { id: 27, section: "Academic Skill Priorities", question: "The student report should guide them to:", options: { A: "Use creativity meaningfully", B: "Manage emotions", C: "Plan work", D: "Take consistent action" } },
  { id: 28, section: "Academic Skill Priorities", question: "The school wants to measure student tendencies in:", options: { A: "Creative risk-taking", B: "Motivation & engagement", C: "Organizational structure", D: "Reliability & discipline" } },
  { id: 29, section: "Academic Skill Priorities", question: "Academic coaching would benefit most from data on:", options: { A: "Creativity", B: "Relationships", C: "Planning", D: "Execution" } },
  { id: 30, section: "Academic Skill Priorities", question: "Which is currently the biggest academic barrier?", options: { A: "Lack of creative thinking", B: "Low student engagement", C: "Poor organization", D: "Weak follow-through" } },

  // SECTION 3 — Student Motivation & Behavior
  { id: 31, section: "Student Motivation & Behavior", question: "What drives student engagement at your school?", options: { A: "Interesting ideas", B: "Strong relationships", C: "Clear routines", D: "Urgent deadlines" } },
  { id: 32, section: "Student Motivation & Behavior", question: "Students disengage most when:", options: { A: "Lessons feel repetitive", B: "They feel disconnected", C: "They feel unprepared", D: "Tasks seem overwhelming" } },
  { id: 33, section: "Student Motivation & Behavior", question: "You want insight into what motivates a student to:", options: { A: "Think", B: "Connect", C: "Prepare", D: "Do" } },
  { id: 34, section: "Student Motivation & Behavior", question: "The student report should help students understand:", options: { A: "What inspires them", B: "What connects them", C: "What grounds them", D: "What drives them" } },
  { id: 35, section: "Student Motivation & Behavior", question: "The biggest behavior issue comes from:", options: { A: "Boredom", B: "Emotional conflict", C: "Poor organization", D: "Avoidance" } },
  { id: 36, section: "Student Motivation & Behavior", question: "Students with unproductive patterns usually lack:", options: { A: "Creative identity", B: "Emotional self-awareness", C: "Planning skills", D: "Motivation or drive" } },
  { id: 37, section: "Student Motivation & Behavior", question: "You want the assessment to help identify:", options: { A: "Idea-driven students", B: "Relationship-driven students", C: "Structure-driven students", D: "Action-driven students" } },
  { id: 38, section: "Student Motivation & Behavior", question: "The report should show a student's:", options: { A: "Creative strengths", B: "Motivational strengths", C: "Organizational strengths", D: "Productivity strengths" } },
  { id: 39, section: "Student Motivation & Behavior", question: "Students need help understanding their:", options: { A: "Creative habits", B: "Emotional triggers", C: "Organization gaps", D: "Motivation cycles" } },
  { id: 40, section: "Student Motivation & Behavior", question: "Behavior interventions work best when they focus on:", options: { A: "Engaging ideas", B: "Relationships", C: "Structure", D: "Clear expectations" } },
  { id: 41, section: "Student Motivation & Behavior", question: "Your school's behavior philosophy is closest to:", options: { A: "Engagement → Behavior", B: "Relationship → Behavior", C: "Structure → Behavior", D: "Accountability → Behavior" } },
  { id: 42, section: "Student Motivation & Behavior", question: "Discipline issues usually stem from:", options: { A: "Lack of interest", B: "Social stress", C: "Chaos or confusion", D: "No sense of urgency" } },
  { id: 43, section: "Student Motivation & Behavior", question: "The assessment should reveal how students:", options: { A: "Explore interests", B: "Navigate relationships", C: "Plan responsibilities", D: "Execute tasks" } },
  { id: 44, section: "Student Motivation & Behavior", question: "Students would improve behavior most by:", options: { A: "Increasing creativity", B: "Fixing emotional patterns", C: "Improving organization", D: "Building discipline" } },
  { id: 45, section: "Student Motivation & Behavior", question: "The student report should help students avoid:", options: { A: "Creative overwhelm", B: "Emotional breakdowns", C: "Missed deadlines", D: "Procrastination" } },

  // SECTION 4 — Social-Emotional Skills
  { id: 46, section: "Social-Emotional Skills", question: "The school values students who can:", options: { A: "Think uniquely", B: "Empathize deeply", C: "Stay grounded", D: "Stay ambitious" } },
  { id: 47, section: "Social-Emotional Skills", question: "Most student conflicts arise because of:", options: { A: "Miscommunication", B: "Emotional reactivity", C: "Planning issues", D: "Poor impulse control" } },
  { id: 48, section: "Social-Emotional Skills", question: "You want student SEL profiles to focus on:", options: { A: "Creative expression", B: "Emotional intelligence", C: "Self-management", D: "Self-discipline" } },
  { id: 49, section: "Social-Emotional Skills", question: "Students struggle most with:", options: { A: "Expressing ideas", B: "Handling emotions", C: "Managing time", D: "Staying focused" } },
  { id: 50, section: "Social-Emotional Skills", question: "Counselors want more info on student:", options: { A: "Creative identity", B: "Emotional triggers", C: "Planning tendencies", D: "Motivation cycles" } },
  { id: 51, section: "Social-Emotional Skills", question: "Students would benefit from SEL insights that show:", options: { A: "Their creative modes", B: "Their emotional patterns", C: "Their organizational strengths", D: "Their drive patterns" } },
  { id: 52, section: "Social-Emotional Skills", question: "SEL breakdowns usually occur when:", options: { A: "Students feel limited", B: "Students feel unsupported", C: "Students feel overwhelmed", D: "Students feel stuck" } },
  { id: 53, section: "Social-Emotional Skills", question: "You want the report to reinforce:", options: { A: "Confidence", B: "Empathy", C: "Responsibility", D: "Initiative" } },
  { id: 54, section: "Social-Emotional Skills", question: "Students who need emotional support often lack:", options: { A: "Creative outlets", B: "Safe relationships", C: "Predictable environments", D: "Motivational structure" } },
  { id: 55, section: "Social-Emotional Skills", question: "SEL development at your school should improve:", options: { A: "Creative risk-taking", B: "Social awareness", C: "Self-management", D: "Self-determination" } },
  { id: 56, section: "Social-Emotional Skills", question: "Students thrive when they feel:", options: { A: "Inspired", B: "Understood", C: "Organized", D: "Motivated" } },
  { id: 57, section: "Social-Emotional Skills", question: "Social issues typically arise when students:", options: { A: "Don't express ideas", B: "Don't communicate emotions", C: "Don't plan interactions", D: "Don't take initiative" } },
  { id: 58, section: "Social-Emotional Skills", question: "The assessment should include SEL feedback about:", options: { A: "Personal expression", B: "Emotional health", C: "Executive functioning", D: "Work patterns" } },
  { id: 59, section: "Social-Emotional Skills", question: "SEL interventions should begin by addressing:", options: { A: "Creative outlets", B: "Emotional needs", C: "Environmental structure", D: "Academic habits" } },
  { id: 60, section: "Social-Emotional Skills", question: "Students grow emotionally when they receive:", options: { A: "Creative opportunities", B: "Emotional validation", C: "Organizational tools", D: "Motivational support" } },

  // SECTION 5 — Executive Functioning & Organization
  { id: 61, section: "Executive Functioning & Organization", question: "Students struggle most with:", options: { A: "Brainstorming structure", B: "Remembering deadlines", C: "Organizing materials", D: "Staying consistent" } },
  { id: 62, section: "Executive Functioning & Organization", question: "Executive functioning support should prioritize:", options: { A: "Creative planning", B: "Emotional regulation", C: "Time management", D: "Work completion" } },
  { id: 63, section: "Executive Functioning & Organization", question: "What issue most commonly hurts grades?", options: { A: "Difficulty generating ideas", B: "Emotional overwhelm", C: "Disorganized work habits", D: "Missing assignments" } },
  { id: 64, section: "Executive Functioning & Organization", question: "The student report should tell students more about their:", options: { A: "Creative work habits", B: "Emotional tendencies", C: "Organizational patterns", D: "Productivity style" } },
  { id: 65, section: "Executive Functioning & Organization", question: "Students need the most help developing:", options: { A: "Idea structure", B: "Self-awareness", C: "Study routines", D: "Motivation cycles" } },
  { id: 66, section: "Executive Functioning & Organization", question: "When students fall behind, it's usually because:", options: { A: "They can't start", B: "They feel discouraged", C: "They lose track", D: "They stop trying" } },
  { id: 67, section: "Executive Functioning & Organization", question: "Teachers want insight into which student habit?", options: { A: "How they brainstorm", B: "How they handle emotions", C: "How they organize tasks", D: "How they push through difficulty" } },
  { id: 68, section: "Executive Functioning & Organization", question: "Effective EF interventions focus on:", options: { A: "Creative clarity", B: "Emotional coping", C: "Planning systems", D: "Daily productivity" } },
  { id: 69, section: "Executive Functioning & Organization", question: "Students who fail to turn in work usually lack:", options: { A: "Clarity on expectations", B: "Emotional safety", C: "Organized steps", D: "Urgency" } },
  { id: 70, section: "Executive Functioning & Organization", question: "You want students to understand their:", options: { A: "Creative process", B: "Emotional patterns", C: "Planning systems", D: "Action cycles" } },
  { id: 71, section: "Executive Functioning & Organization", question: "EF weaknesses are most visible when students:", options: { A: "Overthink ideas", B: "Shut down emotionally", C: "Lose track of tasks", D: "Delay action" } },
  { id: 72, section: "Executive Functioning & Organization", question: "The school wants more insight into student:", options: { A: "Creative decision-making", B: "Social decision-making", C: "Organizational decision-making", D: "Action decision-making" } },
  { id: 73, section: "Executive Functioning & Organization", question: "The assessment should diagnose EF by measuring:", options: { A: "Creative approaches", B: "Emotional responses", C: "Planning habits", D: "Productivity habits" } },
  { id: 74, section: "Executive Functioning & Organization", question: "Students improve EF fastest when given:", options: { A: "Creative frameworks", B: "Emotional support", C: "Organizational templates", D: "Clear goals" } },
  { id: 75, section: "Executive Functioning & Organization", question: "EF coaching should focus on:", options: { A: "Idea focus", B: "Emotional resilience", C: "Planning consistency", D: "Performance stamina" } },

  // SECTION 6 — Social Dynamics & Peer Relationships
  { id: 76, section: "Social Dynamics & Peer Relationships", question: "You want insights into how students:", options: { A: "Express themselves creatively", B: "Build relationships", C: "Communicate responsibilities", D: "Support peers" } },
  { id: 77, section: "Social Dynamics & Peer Relationships", question: "Most peer conflicts come from students:", options: { A: "Misreading ideas", B: "Misreading emotions", C: "Misreading expectations", D: "Misreading social cues" } },
  { id: 78, section: "Social Dynamics & Peer Relationships", question: "Students need help understanding their:", options: { A: "Creative identity", B: "Social identity", C: "Role in group work", D: "Impact on team outcomes" } },
  { id: 79, section: "Social Dynamics & Peer Relationships", question: "The student report should highlight:", options: { A: "Creative participation", B: "Interpersonal habits", C: "Group role tendencies", D: "Work contributions" } },
  { id: 80, section: "Social Dynamics & Peer Relationships", question: "Social issues arise when students:", options: { A: "Suppress ideas", B: "Suppress emotions", C: "Avoid responsibilities", D: "Avoid participation" } },
  { id: 81, section: "Social Dynamics & Peer Relationships", question: "Teachers want more insight into:", options: { A: "Student voice", B: "Peer relationships", C: "Group work leadership", D: "Group work consistency" } },
  { id: 82, section: "Social Dynamics & Peer Relationships", question: "The assessment should measure how students:", options: { A: "Generate ideas in groups", B: "Motivate peers", C: "Help organize tasks", D: "Drive progress" } },
  { id: 83, section: "Social Dynamics & Peer Relationships", question: "Student group work fails when:", options: { A: "No one suggests ideas", B: "Peers don't get along", C: "No one organizes roles", D: "No one executes tasks" } },
  { id: 84, section: "Social Dynamics & Peer Relationships", question: "You want group roles shown as:", options: { A: "Idea contributors", B: "Relationship builders", C: "Organizers", D: "Drivers" } },
  { id: 85, section: "Social Dynamics & Peer Relationships", question: "The report should reveal what motivates students socially:", options: { A: "Expression", B: "Belonging", C: "Stability", D: "Achievement" } },
  { id: 86, section: "Social Dynamics & Peer Relationships", question: "Students struggle socially when they:", options: { A: "Lack creative outlets", B: "Lack emotional support", C: "Lack structure", D: "Lack shared goals" } },
  { id: 87, section: "Social Dynamics & Peer Relationships", question: "Your student culture prioritizes:", options: { A: "Self-expression", B: "Respect & empathy", C: "Responsibility", D: "Productivity" } },
  { id: 88, section: "Social Dynamics & Peer Relationships", question: "Friendships often shift when students:", options: { A: "Change interests", B: "Change emotional needs", C: "Change routines", D: "Change motivations" } },
  { id: 89, section: "Social Dynamics & Peer Relationships", question: "SEL teams want to understand student:", options: { A: "Expression patterns", B: "Emotional cycles", C: "Organizational habits", D: "Behavioral triggers" } },
  { id: 90, section: "Social Dynamics & Peer Relationships", question: "Healthy peer relationships grow when students:", options: { A: "Share creative interests", B: "Communicate clearly", C: "Set boundaries", D: "Support each other's goals" } },

  // SECTION 7 — Classroom Engagement & Learning Identity
  { id: 91, section: "Classroom Engagement & Learning Identity", question: "Students engage most with:", options: { A: "Creative lessons", B: "Supportive teachers", C: "Structured tasks", D: "Fast-paced activities" } },
  { id: 92, section: "Classroom Engagement & Learning Identity", question: "Disengaged students usually need:", options: { A: "Creative stimulation", B: "Emotional reassurance", C: "Clear steps", D: "A reason to act" } },
  { id: 93, section: "Classroom Engagement & Learning Identity", question: "You want the assessment to reveal how students:", options: { A: "Learn creatively", B: "Learn socially", C: "Learn structurally", D: "Learn through action" } },
  { id: 94, section: "Classroom Engagement & Learning Identity", question: "The student report should help students understand:", options: { A: "What sparks ideas", B: "What builds confidence", C: "What boosts clarity", D: "What improves effort" } },
  { id: 95, section: "Classroom Engagement & Learning Identity", question: "Students lose interest when:", options: { A: "Lessons lack creativity", B: "Lessons lack connection", C: "Lessons lack structure", D: "Lessons lack relevance" } },
  { id: 96, section: "Classroom Engagement & Learning Identity", question: "Students participate most when:", options: { A: "There's freedom to explore", B: "They feel safe to speak", C: "They know what's expected", D: "They must take action" } },
  { id: 97, section: "Classroom Engagement & Learning Identity", question: "Learning identity is shaped by:", options: { A: "Passion", B: "Belonging", C: "Organization", D: "Work ethic" } },
  { id: 98, section: "Classroom Engagement & Learning Identity", question: "You want to understand student:", options: { A: "Creative profiles", B: "Social profiles", C: "Study profiles", D: "Work profiles" } },
  { id: 99, section: "Classroom Engagement & Learning Identity", question: "Students who freeze up typically lack:", options: { A: "Idea clarity", B: "Emotional safety", C: "Step-by-step plans", D: "Motivation" } },
  { id: 100, section: "Classroom Engagement & Learning Identity", question: "You want to know how students respond to:", options: { A: "Open-ended tasks", B: "Group work", C: "Organization-heavy work", D: "High-pressure work" } },
  { id: 101, section: "Classroom Engagement & Learning Identity", question: "Engagement improves most when lessons:", options: { A: "Are creative", B: "Are relational", C: "Are structured", D: "Allow movement" } },
  { id: 102, section: "Classroom Engagement & Learning Identity", question: "The student assessment should measure:", options: { A: "Exploratory thinking", B: "Social confidence", C: "Planning mindset", D: "Action mindset" } },
  { id: 103, section: "Classroom Engagement & Learning Identity", question: "Students enjoy learning most when they feel:", options: { A: "Inspired", B: "Connected", C: "Prepared", D: "Motivated" } },
  { id: 104, section: "Classroom Engagement & Learning Identity", question: "Students show mastery when they:", options: { A: "Create", B: "Collaborate", C: "Organize", D: "Execute" } },
  { id: 105, section: "Classroom Engagement & Learning Identity", question: "Engagement dips when students:", options: { A: "Feel restricted", B: "Feel unseen", C: "Feel confused", D: "Feel overwhelmed" } },

  // SECTION 8 — College/Career Readiness & Future Skills
  { id: 106, section: "College/Career Readiness & Future Skills", question: "You want students to develop:", options: { A: "Creativity for future careers", B: "Emotional intelligence for life", C: "Organization for adulthood", D: "Motivation for achievement" } },
  { id: 107, section: "College/Career Readiness & Future Skills", question: "Guidance counselors want more insight into student:", options: { A: "Interests", B: "Personality", C: "Responsibility", D: "Drive" } },
  { id: 108, section: "College/Career Readiness & Future Skills", question: "College readiness is most affected by:", options: { A: "Innovation", B: "Emotional balance", C: "Planning skills", D: "Work habits" } },
  { id: 109, section: "College/Career Readiness & Future Skills", question: "Career readiness depends on:", options: { A: "Original ideas", B: "Communication skills", C: "Organizational skills", D: "Consistency" } },
  { id: 110, section: "College/Career Readiness & Future Skills", question: "You want the report to guide students by showing:", options: { A: "Their creative strengths", B: "Their interpersonal strengths", C: "Their academic habits", D: "Their motivational style" } },
  { id: 111, section: "College/Career Readiness & Future Skills", question: "Students struggle imagining the future because:", options: { A: "They don't explore ideas", B: "They lack confidence", C: "They lack planning skills", D: "They lack momentum" } },
  { id: 112, section: "College/Career Readiness & Future Skills", question: "The assessment should reveal student:", options: { A: "Passions", B: "Values", C: "Habits", D: "Drive patterns" } },
  { id: 113, section: "College/Career Readiness & Future Skills", question: "Post-high-school counseling would improve with insight into:", options: { A: "Student creativity", B: "Student emotions", C: "Student organization", D: "Student discipline" } },
  { id: 114, section: "College/Career Readiness & Future Skills", question: "Students feel future-ready when they:", options: { A: "Are inspired", B: "Feel supported", C: "Have a plan", D: "Take initiative" } },
  { id: 115, section: "College/Career Readiness & Future Skills", question: "Future success relies on:", options: { A: "Innovation", B: "Emotional health", C: "Structure", D: "Persistence" } },
  { id: 116, section: "College/Career Readiness & Future Skills", question: "Students make the best long-term decisions when they:", options: { A: "Explore ideas", B: "Explore feelings", C: "Explore details", D: "Explore outcomes" } },
  { id: 117, section: "College/Career Readiness & Future Skills", question: "Schools need more data on student:", options: { A: "Creative potential", B: "Emotional resilience", C: "Planning abilities", D: "Work style" } },
  { id: 118, section: "College/Career Readiness & Future Skills", question: "You want the student report to connect to:", options: { A: "Elective choices", B: "Counseling support", C: "Study skills programs", D: "Career exposure programs" } },
  { id: 119, section: "College/Career Readiness & Future Skills", question: "Students thrive after graduation when they understand:", options: { A: "Their creative gifts", B: "Their emotional patterns", C: "Their organizational style", D: "Their motivational cycles" } },
  { id: 120, section: "College/Career Readiness & Future Skills", question: "The custom student assessment should prepare students to:", options: { A: "Innovate", B: "Relate", C: "Organize", D: "Achieve" } },

  // SECTION 9 — Schoolwide Priorities & Culture Alignment
  { id: 121, section: "Schoolwide Priorities & Culture Alignment", question: "You want the assessment to reinforce:", options: { A: "Creativity", B: "Community", C: "Structure", D: "Achievement" } },
  { id: 122, section: "Schoolwide Priorities & Culture Alignment", question: "Student culture improves most when students:", options: { A: "Express themselves", B: "Respect each other", C: "Follow routines", D: "Work hard" } },
  { id: 123, section: "Schoolwide Priorities & Culture Alignment", question: "You want the assessment to help identify:", options: { A: "Emerging creators", B: "Natural connectors", C: "Organizational thinkers", D: "High-drive workers" } },
  { id: 124, section: "Schoolwide Priorities & Culture Alignment", question: "Schoolwide initiatives should focus on:", options: { A: "Creativity", B: "SEL", C: "Executive functioning", D: "Performance" } },
  { id: 125, section: "Schoolwide Priorities & Culture Alignment", question: "Your school's biggest systemic weakness is:", options: { A: "Lack of innovative thinking", B: "Lack of emotional awareness", C: "Lack of structure", D: "Lack of urgency" } },
  { id: 126, section: "Schoolwide Priorities & Culture Alignment", question: "The assessment should integrate into:", options: { A: "Creative programs", B: "Advisory/SEL", C: "Study skills programs", D: "Academic bootcamps" } },
  { id: 127, section: "Schoolwide Priorities & Culture Alignment", question: "School culture strengthens when students:", options: { A: "Share ideas", B: "Support peers", C: "Stay consistent", D: "Take initiative" } },
  { id: 128, section: "Schoolwide Priorities & Culture Alignment", question: "Teachers want more insight into student:", options: { A: "Passions", B: "Behavior cues", C: "Study habits", D: "Work ethic" } },
  { id: 129, section: "Schoolwide Priorities & Culture Alignment", question: "You want reports to connect to school priorities like:", options: { A: "Innovation labs", B: "School climate", C: "Organization systems", D: "Achievement goals" } },
  { id: 130, section: "Schoolwide Priorities & Culture Alignment", question: "Administrators want to use student profiles to:", options: { A: "Personalize learning", B: "Improve relationships", C: "Improve routines", D: "Improve outcomes" } },
  { id: 131, section: "Schoolwide Priorities & Culture Alignment", question: "A custom student assessment should feel:", options: { A: "Creative", B: "Supportive", C: "Structured", D: "Motivational" } },
  { id: 132, section: "Schoolwide Priorities & Culture Alignment", question: "The data should be used to:", options: { A: "Encourage creativity", B: "Improve SEL", C: "Strengthen study habits", D: "Increase performance" } },
  { id: 133, section: "Schoolwide Priorities & Culture Alignment", question: "The assessment should categorize students by:", options: { A: "Creative tendencies", B: "Social tendencies", C: "Organizational tendencies", D: "Motivational tendencies" } },
  { id: 134, section: "Schoolwide Priorities & Culture Alignment", question: "Student culture improves when the school emphasizes:", options: { A: "Expression", B: "Empathy", C: "Structure", D: "Discipline" } },
  { id: 135, section: "Schoolwide Priorities & Culture Alignment", question: "The student report should encourage students to:", options: { A: "Create boldly", B: "Connect authentically", C: "Organize consistently", D: "Act decisively" } },

  // SECTION 10 — Design, Tone & Output of the Student Report
  { id: 136, section: "Design, Tone & Output of the Student Report", question: "The tone of the student report should be:", options: { A: "Creative", B: "Encouraging", C: "Structured", D: "Direct" } },
  { id: 137, section: "Design, Tone & Output of the Student Report", question: "The visual style should be:", options: { A: "Vibrant", B: "Welcoming", C: "Organized", D: "Minimal" } },
  { id: 138, section: "Design, Tone & Output of the Student Report", question: "Strengths should be framed as:", options: { A: "Creative gifts", B: "Social strengths", C: "Organizational habits", D: "Drive strengths" } },
  { id: 139, section: "Design, Tone & Output of the Student Report", question: "Growth areas should be framed as:", options: { A: "Opportunities", B: "Emotional tools", C: "Planning improvements", D: "Action steps" } },
  { id: 140, section: "Design, Tone & Output of the Student Report", question: "Students should walk away feeling:", options: { A: "Inspired", B: "Understood", C: "Prepared", D: "Motivated" } },
  { id: 141, section: "Design, Tone & Output of the Student Report", question: "The report should emphasize student:", options: { A: "Imagination", B: "Self-awareness", C: "Study skills", D: "Work ethic" } },
  { id: 142, section: "Design, Tone & Output of the Student Report", question: "Reports should help students:", options: { A: "Explore ideas", B: "Understand emotions", C: "Organize tasks", D: "Take action" } },
  { id: 143, section: "Design, Tone & Output of the Student Report", question: "You want the report to guide students toward:", options: { A: "Creativity", B: "Relationships", C: "Planning", D: "Execution" } },
  { id: 144, section: "Design, Tone & Output of the Student Report", question: "Student suggestions should focus on:", options: { A: "Creative exercises", B: "SEL strategies", C: "Planning routines", D: "Productivity habits" } },
  { id: 145, section: "Design, Tone & Output of the Student Report", question: "The ideal report length is:", options: { A: "Long & inspirational", B: "Medium & personal", C: "Structured & concise", D: "Minimal & direct" } },
  { id: 146, section: "Design, Tone & Output of the Student Report", question: "Visual elements should include:", options: { A: "Creative icons", B: "People-focused graphics", C: "Charts & steps", D: "Simple diagrams" } },
  { id: 147, section: "Design, Tone & Output of the Student Report", question: "The report should help educators understand:", options: { A: "Student creativity", B: "Student emotions", C: "Student organization", D: "Student motivation" } },
  { id: 148, section: "Design, Tone & Output of the Student Report", question: "The school wants reports that are:", options: { A: "Fun", B: "Warm", C: "Clear", D: "Actionable" } },
  { id: 149, section: "Design, Tone & Output of the Student Report", question: "You want the assessment to help students succeed by:", options: { A: "Unlocking creativity", B: "Strengthening relationships", C: "Improving organization", D: "Increasing motivation" } },
  { id: 150, section: "Design, Tone & Output of the Student Report", question: "The final student report should feel like:", options: { A: "A creative guide", B: "A personal mirror", C: "A planning roadmap", D: "A motivation blueprint" } },
];

export const studentSections = [
  "School Values & Student Philosophy",
  "Academic Skill Priorities",
  "Student Motivation & Behavior",
  "Social-Emotional Skills",
  "Executive Functioning & Organization",
  "Social Dynamics & Peer Relationships",
  "Classroom Engagement & Learning Identity",
  "College/Career Readiness & Future Skills",
  "Schoolwide Priorities & Culture Alignment",
  "Design, Tone & Output of the Student Report"
];
