project_id = "qbuxoetprodjxpagfkoi"

[functions.create-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.voiceAssessment]
verify_jwt = false

[functions.initiate-voice-call]
verify_jwt = false

[functions.create-company]
verify_jwt = false

[functions.invite-company-user]
verify_jwt = true