// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbuxoetprodjxpagfkoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFidXhvZXRwcm9kanhwYWdma29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDMzOTcsImV4cCI6MjA2OTU3OTM5N30.XWrpWtw6li21hAeIpeYImOdi20sVoQ7Hbh1Bd3zMBWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});