// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbdsjimfpsehqrmfxocg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZHNqaW1mcHNlaHFybWZ4b2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTgxMTMsImV4cCI6MjA2NzU5NDExM30.5DknZme68zX7-_6EJuLiUueSl389mLrBHY3YhMeBssw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});